<?php

return [
    'niveaux' => [
        ['code' => '1ap', 'label' => '1ere Annee Primaire'],
        ['code' => '2ap', 'label' => '2eme Annee Primaire'],
        ['code' => '3ap', 'label' => '3eme Annee Primaire'],
        ['code' => '4ap', 'label' => '4eme Annee Primaire'],
        ['code' => '5ap', 'label' => '5eme Annee Primaire'],
        ['code' => '6ap', 'label' => '6eme Annee Primaire'],
        ['code' => '1ac', 'label' => '1ere Annee College'],
        ['code' => '2ac', 'label' => '2eme Annee College'],
        ['code' => '3ac', 'label' => '3eme Annee College'],
        ['code' => 'tc', 'label' => 'Tronc Commun'],
        ['code' => '1bac', 'label' => '1ere Annee Baccalaureat'],
        ['code' => '2bac', 'label' => '2eme Annee Baccalaureat'],
    ],

    'filieres_by_niveau' => [
        '1ap' => ['General'],
        '2ap' => ['General'],
        '3ap' => ['General'],
        '4ap' => ['General'],
        '5ap' => ['General'],
        '6ap' => ['General'],
        '1ac' => ['General'],
        '2ac' => ['General'],
        '3ac' => ['General'],
        'tc' => ['Sciences et Technologies', 'Lettres et Sciences Humaines'],
        '1bac' => ['Sciences Experimentales', 'Sciences Mathematiques', 'Sciences Economiques', 'Lettres Modernes'],
        '2bac' => ['Sciences Experimentales', 'Sciences Mathematiques', 'Sciences Economiques', 'Lettres Modernes', 'Lettres et Sciences Humaines'],
    ],

    'pricing_by_niveau_filiere' => [
        '1ap' => ['General' => 1200],
        '2ap' => ['General' => 1200],
        '3ap' => ['General' => 1300],
        '4ap' => ['General' => 1300],
        '5ap' => ['General' => 1400],
        '6ap' => ['General' => 1400],
        '1ac' => ['General' => 1600],
        '2ac' => ['General' => 1700],
        '3ac' => ['General' => 1800],
        'tc' => [
            'Sciences et Technologies' => 2100,
            'Lettres et Sciences Humaines' => 1900,
        ],
        '1bac' => [
            'Sciences Experimentales' => 2500,
            'Sciences Mathematiques' => 2600,
            'Sciences Economiques' => 2300,
            'Lettres Modernes' => 2100,
        ],
        '2bac' => [
            'Sciences Experimentales' => 3000,
            'Sciences Mathematiques' => 3200,
            'Sciences Economiques' => 2700,
            'Lettres Modernes' => 2400,
            'Lettres et Sciences Humaines' => 2350,
        ],
    ],

    'matieres' => [
        ['nom' => 'Mathematiques', 'coefficient' => 5],
        ['nom' => 'Physique Chimie', 'coefficient' => 4],
        ['nom' => 'Sciences de la Vie et de la Terre', 'coefficient' => 4],
        ['nom' => 'Arabe', 'coefficient' => 4],
        ['nom' => 'Francais', 'coefficient' => 4],
        ['nom' => 'Anglais', 'coefficient' => 3],
        ['nom' => 'Espagnol', 'coefficient' => 2],
        ['nom' => 'Histoire Geographie', 'coefficient' => 3],
        ['nom' => 'Philosophie', 'coefficient' => 2],
        ['nom' => 'Informatique', 'coefficient' => 3],
        ['nom' => 'Education Islamique', 'coefficient' => 2],
        ['nom' => 'Education Physique', 'coefficient' => 2],
        ['nom' => 'Arts Plastiques', 'coefficient' => 1],
        ['nom' => 'Economie Generale', 'coefficient' => 3],
        ['nom' => 'Comptabilite et Math Financieres', 'coefficient' => 3],
        ['nom' => 'Science de l Ingenieur', 'coefficient' => 4],
        ['nom' => 'Technologie', 'coefficient' => 2],
        ['nom' => 'Communication et Soft Skills', 'coefficient' => 1],
    ],
];
